version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/cli"
    schedule:
      interval: "weekly"
    source-branch: "main"
    target-branch: "staging"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "cargo"
    directory: "/api"
    schedule:
      interval: "weekly"
    source-branch: "main"
    target-branch: "staging"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "weekly"
    source-branch: "main"
    target-branch: "staging"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    source-branch: "main"
    target-branch: "staging"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
